# Generated by Django 3.2.7 on 2021-10-25 08:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='item_code',
            field=models.CharField(default=users.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
