# Generated by Django 3.2.7 on 2021-10-25 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_alter_buyitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_id', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyitem',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
