# Generated by Django 3.2.7 on 2021-10-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211025_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_item_id', to='items.item'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_item_id', to='items.item'),
        ),
    ]
