# Generated by Django 3.2.7 on 2021-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='buyer_name',
            field=models.CharField(default='Denny', max_length=250),
            preserve_default=False,
        ),
    ]
