# Generated by Django 3.2.7 on 2021-10-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_buyitem_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
