# Generated by Django 3.2.7 on 2021-10-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_responsenotitobuyer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsenotitobuyer',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='response_item_id', to='items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsenotitobuyer',
            name='item_code',
            field=models.CharField(default='FMKECH', max_length=8),
            preserve_default=False,
        ),
    ]
