# Generated by Django 3.2.7 on 2021-10-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20211026_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsenotitobuyer',
            name='item',
        ),
    ]
