# Generated by Django 3.2.7 on 2021-10-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_responsenotitobuyer_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsenotitobuyer',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='response_item_id', to='items.item'),
            preserve_default=False,
        ),
    ]
