# Generated by Django 3.2.7 on 2021-10-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_responsenotitobuyer_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsenotitobuyer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_item_id', to='items.item'),
        ),
    ]
